In [6]:
import pandas as pd
import numpy as np 

df = pd.DataFrame(np.arange(0,20).reshape(4,5),index=["r1","r2","r3","r4"],columns=["c1","c2","c3","c4","c5"])
df.head()

    c1  c2  c3  c4  c5
r1   0   1   2   3   4
r2   5   6   7   8   9
r3  10  11  12  13  14
r4  15  16  17  18  19

In [7]:
df.to_csv("datefile.csv")

In [8]:
var_name = pd.DataFrame(np.arange(1,31).reshape(3,10),index =["r1","r2","r3"],columns=[1,2,3,4,5,6,7,8,9,10])
var_name.head()

    1   2   3   4   5   6   7   8   9   10
r1   1   2   3   4   5   6   7   8   9  10
r2  11  12  13  14  15  16  17  18  19  20
r3  21  22  23  24  25  26  27  28  29  30

In [13]:
var_name.to_excel("number.xlsx")

In [18]:
print(type(var_name.loc["r2"]))

<class 'pandas.core.series.Series'>

In [21]:
print(var_name.iloc[:,:6])

     1   2   3   4   5   6
r1   1   2   3   4   5   6
r2  11  12  13  14  15  16
r3  21  22  23  24  25  26

In [23]:
var_name.values

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [26]:
var_name.values.shape

(3, 10)

In [33]:
var_name.isnull().sum()

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64

In [34]:
var_name

    1   2   3   4   5   6   7   8   9   10
r1   1   2   3   4   5   6   7   8   9  10
r2  11  12  13  14  15  16  17  18  19  20
r3  21  22  23  24  25  26  27  28  29  30

In [41]:
var_name["r1"].value_counts()

KeyError: 'r1'

In [39]:
var_name[1].value_counts()

1
1     1
11    1
21    1
Name: count, dtype: int64